import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { encode, openTiff, TIFF_MAX_PIXELS } from '../../src/index.js';

/**
 * Generated by `crates/papyra-tiff/tests/fixtures/generate.py`, and asserted against
 * on the Rust side too: a dark square over x 16..48, y 12..36 of a 70x50 page.
 */
const FIXTURES = join(
  import.meta.dir,
  '..',
  '..',
  '..',
  '..',
  'crates',
  'papyra-tiff',
  'tests',
  'fixtures',
);
const fixture = (name: string) => readFileSync(join(FIXTURES, name));

const pixel = (
  page: { data: Uint8Array; stride: number },
  x: number,
  y: number,
) =>
  Array.from(
    page.data.subarray(y * page.stride + x * 4, y * page.stride + x * 4 + 4),
  );

describe('openTiff', () => {
  test('lists a Group 4 page with its resolution', async () => {
    const tiff = await openTiff(fixture('g4.tif'));
    expect(tiff.pageCount).toBe(1);
    expect(tiff.pages[0]).toEqual({
      width: 70,
      height: 50,
      dpi: { x: 300, y: 300 },
      compression: 'ccitt-g4',
      bitsPerSample: 1,
      samplesPerPixel: 1,
      orientation: 1,
    });
  });

  test('renders a page as RGBA, the shape paintToCanvas takes', async () => {
    const tiff = await openTiff(fixture('g4.tif'));
    const page = await tiff.renderPage(0);
    expect([page.width, page.height, page.stride, page.format]).toEqual([
      70,
      50,
      280,
      'rgba8',
    ]);
    expect(pixel(page, 32, 24)).toEqual([0, 0, 0, 255]);
    expect(pixel(page, 0, 0)).toEqual([255, 255, 255, 255]);
  });

  test('skips a reduced-resolution directory and pages through the rest', async () => {
    const tiff = await openTiff(new Blob([fixture('multipage.tif')]));
    expect(tiff.pageCount).toBe(3);
    const last = await tiff.renderPage(2);
    expect(pixel(last, 44, 14)).toEqual([0, 0, 0, 255]);
    expect(pixel(last, 45, 14)).toEqual([255, 255, 255, 255]);
  });

  test('reduces to maxWidth and maxPixels, never enlarging', async () => {
    const tiff = await openTiff(fixture('rgb-lzw.tif'));
    const narrow = await tiff.renderPage(0, { maxWidth: 35 });
    expect([narrow.width, narrow.height]).toEqual([35, 25]);
    const small = await tiff.renderPage(0, { maxPixels: 70 * 5 });
    expect(small.width * small.height).toBeLessThanOrEqual(70 * 5);
    const whole = await tiff.renderPage(0, { maxWidth: 10_000 });
    expect(whole.width).toBe(70);
    expect(TIFF_MAX_PIXELS).toBe(4096 * 4096);
  });

  test('applies Orientation to the size it reports and the pixels', async () => {
    const tiff = await openTiff(fixture('orient6.tif'));
    expect([tiff.pages[0]?.width, tiff.pages[0]?.height]).toEqual([50, 70]);
    const page = await tiff.renderPage(0);
    expect(pixel(page, 47, 2)).toEqual([0, 200, 0, 255]);
  });

  test('a rendered page encodes like a PDF page', async () => {
    const page = await (await openTiff(fixture('g4.tif'))).renderPage(0);
    const png = await encode(page, { format: 'png' });
    expect(png.mime).toBe('image/png');
    expect(Array.from(png.bytes.subarray(1, 4))).toEqual([0x50, 0x4e, 0x47]);
  });

  test('refuses what it cannot read, by name', async () => {
    await expect(
      openTiff(new Uint8Array([0x25, 0x50, 0x44, 0x46])),
    ).rejects.toThrow('not a TIFF file');
    const palette = await openTiff(fixture('palette.tif'));
    await expect(palette.renderPage(0)).rejects.toThrow('palette colour');
    await expect(palette.renderPage(1)).rejects.toBeInstanceOf(RangeError);
  });
});
