import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { EncryptedWorkbookError, openWorkbook } from '../../src/index.js';

/**
 * Spreadsheet fixtures are small and checked in, unlike the PDF corpus: they are
 * generated by `crates/papyra-tables/tests/fixtures/generate.py`, and the Rust tests
 * assert the same contents, so both ends of the boundary agree on one file.
 */
const FIXTURES = join(
  import.meta.dir,
  '..',
  '..',
  '..',
  '..',
  'crates',
  'papyra-tables',
  'tests',
  'fixtures',
);
const fixture = (name: string) => readFileSync(join(FIXTURES, name));

describe.each(['xlsx', 'xls', 'ods'])('openWorkbook, %s', (ext) => {
  test('reads the summary sheet through a window', async () => {
    const book = await openWorkbook(fixture(`sample.${ext}`));
    expect(book.format).toBe(ext);
    expect(book.sheets[0]?.name).toBe('Summary');
    expect(book.encoding).toBeUndefined();

    const sheet = await book.sheet('Summary');
    expect([sheet.rows, sheet.cols]).toEqual([5, 4]);

    const cells = sheet.window({ rowStart: 0, rowEnd: 100 });
    expect(cells.rows).toBe(5);
    expect(cells.text(0, 0)).toBe('Item');
    expect(cells.text(2, 0)).toBe('Nuts — M8');
    expect(cells.cell(1, 1)).toEqual({ kind: 'number', value: 12, text: '12' });
    expect(cells.cell(2, 2)).toEqual({
      kind: 'number',
      value: 0.1,
      text: '0.1',
    });
    expect(cells.cell(4, 0)).toEqual({
      kind: 'bool',
      value: true,
      text: 'TRUE',
    });
    expect(cells.text(1, 3)).toBe('2024-03-15');
    expect(cells.text(2, 3)).toBe('2024-03-15T13:30:00');
  });
});

describe('openWorkbook, workbook features', () => {
  test('reports merges, hidden sheets, errors and an offset range', async () => {
    const book = await openWorkbook(fixture('sample.xlsx'));
    const summary = await book.sheet(0);
    expect(summary.merges).toEqual([
      { row: 3, col: 0, lastRow: 3, lastCol: 1 },
    ]);
    expect(summary.window({ rowStart: 4, rowEnd: 5 }).cell(4, 2)).toEqual({
      kind: 'error',
      text: '#DIV/0!',
    });

    expect(book.sheets[1]).toEqual({
      name: 'Hidden',
      kind: 'worksheet',
      visibility: 'hidden',
    });
    const hidden = await book.sheet(1);
    expect([hidden.rows, hidden.cols]).toEqual([10, 6]);
    expect(hidden.window({ rowStart: 9, rowEnd: 10 }).text(9, 5)).toBe('far');
  });

  test('shares one read between callers asking for the same sheet', async () => {
    const book = await openWorkbook(fixture('sample.xlsx'));
    expect(book.sheet(0)).toBe(book.sheet('Summary'));
  });

  test('rejects a sheet that does not exist', async () => {
    const book = await openWorkbook(fixture('sample.xlsx'));
    await expect(book.sheet(9)).rejects.toThrow(RangeError);
    await expect(book.sheet('Nope')).rejects.toThrow(RangeError);
  });

  test('a password-protected xlsx is a typed error', async () => {
    const opening = openWorkbook(fixture('encrypted.xlsx'));
    await expect(opening).rejects.toBeInstanceOf(EncryptedWorkbookError);
    // The tag is the bindings' business; a caller never sees it.
    await expect(opening).rejects.toThrow(
      /^this workbook is password-protected$/,
    );
  });
});

describe('openWorkbook, delimited text', () => {
  test('sniffs the encoding and delimiter of an Excel-on-Windows CSV', async () => {
    // Semicolons because the locale writes 1,5 for one and a half; windows-1252
    // because that is what Excel saves "CSV" as there. é is 0xE9.
    const bytes = new Uint8Array([
      ...new TextEncoder().encode('Name;Amount\nCaf'),
      0xe9,
      ...new TextEncoder().encode(';1,5\n'),
    ]);
    const book = await openWorkbook(bytes);
    expect(book.format).toBe('csv');
    expect(book.delimiter).toBe(';');
    expect(book.encoding).toBe('windows-1252');

    const cells = (await book.sheet(0)).window({ rowStart: 0, rowEnd: 2 });
    expect(cells.text(1, 0)).toBe('Café');
    expect(cells.cell(1, 1)).toEqual({ kind: 'text', text: '1,5' });
  });

  test('keeps a number as written and an identifier as text', async () => {
    const book = await openWorkbook(
      new TextEncoder().encode('zip,qty\n007,2.50\n'),
    );
    const cells = (await book.sheet(0)).window({ rowStart: 0, rowEnd: 2 });
    expect(cells.cell(1, 0)).toEqual({ kind: 'text', text: '007' });
    expect(cells.cell(1, 1)).toEqual({
      kind: 'number',
      value: 2.5,
      text: '2.50',
    });
  });

  test('trusts a .tsv name, and an explicit delimiter over sniffing', async () => {
    const tsv = new File(['a,b\tc\n1,2\t3\n'], 'data.tsv');
    const book = await openWorkbook(tsv);
    expect(book.format).toBe('tsv');
    expect((await book.sheet(0)).cols).toBe(2);

    const piped = await openWorkbook(new TextEncoder().encode('a|b,c\n'), {
      delimiter: ',',
    });
    expect(
      (await piped.sheet(0)).window({ rowStart: 0, rowEnd: 1 }).text(0, 0),
    ).toBe('a|b');
  });

  test('clamps a window that overscans past every edge', async () => {
    const book = await openWorkbook(new TextEncoder().encode('a,b\n1,2\n'));
    const cells = (await book.sheet(0)).window({
      rowStart: -5,
      rowEnd: 1000,
      colStart: -1,
      colEnd: 1000,
    });
    expect([cells.rowStart, cells.colStart, cells.rows, cells.cols]).toEqual([
      0, 0, 2, 2,
    ]);
  });
});
