/**
 * Write the Word document the file preview demo opens.
 *
 * Generated rather than copied, like `make-sample-pdf.ts`, so nothing here carries
 * someone else's licence — and written part by part, so it shows what the renderer
 * is being asked to draw: styles, headings, both kinds of list, a shaded table, an
 * embedded picture, a hyperlink, a footer, and a page break.
 *
 * The zip is stored, not deflated: a few kilobytes either way, and it keeps the
 * script free of dependencies.
 *
 * Usage: bun run scripts/make-sample-docx.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { deflateSync } from 'node:zlib';

const W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const R = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const REL = `${R}`;
const PKG_REL = 'http://schemas.openxmlformats.org/package/2006/relationships';

const xml = (body: string) =>
  `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n${body}`;

/** A run of text, with optional run properties. */
const run = (text: string, props = '') =>
  `<w:r>${props ? `<w:rPr>${props}</w:rPr>` : ''}<w:t xml:space="preserve">${text}</w:t></w:r>`;

const para = (content: string, props = '') =>
  `<w:p>${props ? `<w:pPr>${props}</w:pPr>` : ''}${content}</w:p>`;

const styled = (style: string, text: string) =>
  para(run(text), `<w:pStyle w:val="${style}"/>`);

const listItem = (numId: number, text: string) =>
  para(
    run(text),
    `<w:pStyle w:val="ListParagraph"/><w:numPr><w:ilvl w:val="0"/><w:numId w:val="${numId}"/></w:numPr>`,
  );

const cell = (text: string, header = false, align = 'left') =>
  `<w:tc><w:tcPr><w:tcW w:w="2400" w:type="dxa"/>${
    header ? '<w:shd w:val="clear" w:color="auto" w:fill="1F2937"/>' : ''
  }</w:tcPr>${para(
    run(text, header ? '<w:b/><w:color w:val="FFFFFF"/>' : ''),
    `<w:jc w:val="${align}"/>`,
  )}</w:tc>`;

const ROWS: [string, string, string, string][] = [
  ['Format', 'Renderer', 'Engine', 'Matched by'],
  ['PDF', 'file-preview-pdf', 'papyra (Rust)', 'bytes'],
  ['Spreadsheet', 'file-preview-spreadsheet', 'papyra (Rust)', 'name'],
  ['Word', 'file-preview-docx', 'docx-preview', 'name'],
  ['Markdown', 'file-preview-markdown', 'react-markdown', 'name'],
];

const table = `<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="9600" w:type="dxa"/></w:tblPr><w:tblGrid>${'<w:gridCol w:w="2400"/>'.repeat(4)}</w:tblGrid>${ROWS.map(
  (row, i) =>
    `<w:tr>${row.map((t, j) => cell(t, i === 0, j === 3 ? 'right' : 'left')).join('')}</w:tr>`,
).join('')}</w:tbl>`;

// 2 inches by 1, in EMU.
const CX = 1828800;
const CY = 914400;
const picture = para(
  `<w:r><w:drawing><wp:inline xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"><wp:extent cx="${CX}" cy="${CY}"/><wp:docPr id="1" name="Gradient"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="1" name="gradient.png"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rIdImage"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${CX}" cy="${CY}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r>`,
  '<w:jc w:val="center"/>',
);

const body = [
  styled('Title', 'Quarterly site report'),
  para(
    run('Prepared for the file preview demo. ', '<w:i/>') +
      run('Everything on these pages is generated by ', '<w:i/>') +
      run(
        'scripts/make-sample-docx.ts',
        '<w:rFonts w:ascii="Consolas" w:hAnsi="Consolas"/><w:i/>',
      ) +
      run('.', '<w:i/>'),
  ),
  styled('Heading1', 'Summary'),
  para(
    run('Work is ') +
      run('on schedule', '<w:b/><w:color w:val="2E7D32"/>') +
      run(
        ' for the second phase. Two items need a decision before the next review, and one is ',
      ) +
      run('blocked', '<w:b/><w:color w:val="C62828"/>') +
      run(' on a supplier.'),
  ),
  listItem(1, 'Steel delivery moved to the 14th.'),
  listItem(1, 'Façade samples approved — naïve colour match was close enough.'),
  listItem(1, 'Crane hire extended by two weeks.'),
  styled('Heading2', 'Decisions needed'),
  listItem(2, 'Accept the revised glazing quote.'),
  listItem(2, 'Choose between the two lift suppliers.'),
  styled('Heading1', 'Formats in the preview'),
  table,
  para(''),
  para(
    run('The source is on ') +
      `<w:hyperlink r:id="rIdLink" w:history="1">${run('GitHub', '<w:rStyle w:val="Hyperlink"/>')}</w:hyperlink>` +
      run(
        ', and the table above is drawn from a Word table with a shaded header row.',
      ),
  ),
  para('<w:r><w:br w:type="page"/></w:r>'),
  styled('Heading1', 'Site photograph'),
  para(run('An embedded picture, scaled to two inches by one:')),
  picture,
  styled('Heading2', 'Notes'),
  para(
    run(
      'Layout in the preview is approximate: text, tables, lists and pictures come through well, floating shapes and complex sections less so. Download the file to see it exactly.',
    ),
  ),
].join('');

const document = xml(
  `<w:document xmlns:w="${W}" xmlns:r="${R}"><w:body>${body}<w:sectPr><w:footerReference w:type="default" r:id="rIdFooter"/><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1200" w:bottom="1440" w:left="1200" w:header="720" w:footer="720" w:gutter="0"/></w:sectPr></w:body></w:document>`,
);

const footer = xml(
  `<w:ftr xmlns:w="${W}" xmlns:r="${R}">${para(run('papyra · sample document', '<w:color w:val="6B7280"/><w:sz w:val="18"/>'), '<w:jc w:val="center"/>')}</w:ftr>`,
);

const heading = (id: string, name: string, size: number, color: string) =>
  `<w:style w:type="paragraph" w:styleId="${id}"><w:name w:val="${name}"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="240" w:after="120"/></w:pPr><w:rPr><w:rFonts w:ascii="Calibri Light" w:hAnsi="Calibri Light"/><w:b/><w:color w:val="${color}"/><w:sz w:val="${size}"/></w:rPr></w:style>`;

const styles = xml(
  `<w:styles xmlns:w="${W}"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="160" w:line="259" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults>` +
    `<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>` +
    `<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:after="240"/></w:pPr><w:rPr><w:rFonts w:ascii="Calibri Light" w:hAnsi="Calibri Light"/><w:color w:val="1F2937"/><w:sz w:val="56"/></w:rPr></w:style>` +
    heading('Heading1', 'heading 1', 32, '1D4ED8') +
    heading('Heading2', 'heading 2', 26, '374151') +
    `<w:style w:type="paragraph" w:styleId="ListParagraph"><w:name w:val="List Paragraph"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:after="60"/><w:ind w:left="720"/></w:pPr></w:style>` +
    `<w:style w:type="character" w:styleId="Hyperlink"><w:name w:val="Hyperlink"/><w:rPr><w:color w:val="1D4ED8"/><w:u w:val="single"/></w:rPr></w:style>` +
    `<w:style w:type="table" w:styleId="TableGrid"><w:name w:val="Table Grid"/><w:tblPr><w:tblBorders>${['top', 'left', 'bottom', 'right', 'insideH', 'insideV'].map((s) => `<w:${s} w:val="single" w:sz="4" w:space="0" w:color="9CA3AF"/>`).join('')}</w:tblBorders><w:tblCellMar><w:left w:w="108" w:type="dxa"/><w:right w:w="108" w:type="dxa"/></w:tblCellMar></w:tblPr></w:style>` +
    `</w:styles>`,
);

const level = (format: string, text: string) =>
  `<w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="${format}"/><w:lvlText w:val="${text}"/><w:lvlJc w:val="left"/><w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr></w:lvl>`;

const numbering = xml(
  `<w:numbering xmlns:w="${W}"><w:abstractNum w:abstractNumId="0">${level('bullet', '•')}</w:abstractNum><w:abstractNum w:abstractNumId="1">${level('decimal', '%1.')}</w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num><w:num w:numId="2"><w:abstractNumId w:val="1"/></w:num></w:numbering>`,
);

/** A 2:1 gradient in papyra's accent, so the picture is visibly a picture. */
function gradientPng(width: number, height: number): Uint8Array {
  const raw = new Uint8Array((width * 3 + 1) * height);
  for (let y = 0; y < height; y++) {
    const row = y * (width * 3 + 1);
    for (let x = 0; x < width; x++) {
      const t = (x / width + y / height) / 2;
      raw.set(
        [
          Math.round(0x6e + (0x1f - 0x6e) * t),
          Math.round(0xa8 + (0x29 - 0xa8) * t),
          Math.round(0xfe + (0x37 - 0xfe) * t),
        ],
        row + 1 + x * 3,
      );
    }
  }
  const chunk = (type: string, data: Uint8Array) => {
    const out = new Uint8Array(12 + data.length);
    const view = new DataView(out.buffer);
    view.setUint32(0, data.length);
    out.set(new TextEncoder().encode(type), 4);
    out.set(data, 8);
    view.setUint32(
      8 + data.length,
      Bun.hash.crc32(out.subarray(4, 8 + data.length)),
    );
    return out;
  };
  const ihdr = new Uint8Array(13);
  const view = new DataView(ihdr.buffer);
  view.setUint32(0, width);
  view.setUint32(4, height);
  ihdr.set([8, 2, 0, 0, 0], 8);
  return concat([
    new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', new Uint8Array()),
  ]);
}

const PARTS: [string, string | Uint8Array][] = [
  [
    '[Content_Types].xml',
    xml(
      `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>`,
    ),
  ],
  [
    '_rels/.rels',
    xml(
      `<Relationships xmlns="${PKG_REL}"><Relationship Id="rId1" Type="${REL}/officeDocument" Target="word/document.xml"/></Relationships>`,
    ),
  ],
  ['word/document.xml', document],
  [
    'word/_rels/document.xml.rels',
    xml(
      `<Relationships xmlns="${PKG_REL}"><Relationship Id="rIdStyles" Type="${REL}/styles" Target="styles.xml"/><Relationship Id="rIdNumbering" Type="${REL}/numbering" Target="numbering.xml"/><Relationship Id="rIdFooter" Type="${REL}/footer" Target="footer1.xml"/><Relationship Id="rIdImage" Type="${REL}/image" Target="media/gradient.png"/><Relationship Id="rIdLink" Type="${REL}/hyperlink" Target="https://github.com/BuildQube/Papyra" TargetMode="External"/></Relationships>`,
    ),
  ],
  ['word/styles.xml', styles],
  ['word/numbering.xml', numbering],
  ['word/footer1.xml', footer],
  ['word/media/gradient.png', gradientPng(240, 120)],
];

function concat(chunks: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(chunks.reduce((n, c) => n + c.length, 0));
  let at = 0;
  for (const c of chunks) {
    out.set(c, at);
    at += c.length;
  }
  return out;
}

/** A zip of stored entries: local headers, then the central directory, then its end. */
function zip(parts: [string, string | Uint8Array][]): Uint8Array {
  const locals: Uint8Array[] = [];
  const centrals: Uint8Array[] = [];
  let offset = 0;
  for (const [name, content] of parts) {
    const data =
      typeof content === 'string' ? new TextEncoder().encode(content) : content;
    const path = new TextEncoder().encode(name);
    const crc = Bun.hash.crc32(data);

    const local = new Uint8Array(30 + path.length);
    const l = new DataView(local.buffer);
    l.setUint32(0, 0x04034b50, true);
    l.setUint16(4, 20, true);
    l.setUint32(14, crc, true);
    l.setUint32(18, data.length, true);
    l.setUint32(22, data.length, true);
    l.setUint16(26, path.length, true);
    local.set(path, 30);

    const central = new Uint8Array(46 + path.length);
    const c = new DataView(central.buffer);
    c.setUint32(0, 0x02014b50, true);
    c.setUint16(4, 20, true);
    c.setUint16(6, 20, true);
    c.setUint32(16, crc, true);
    c.setUint32(20, data.length, true);
    c.setUint32(24, data.length, true);
    c.setUint16(28, path.length, true);
    c.setUint32(42, offset, true);
    central.set(path, 46);

    locals.push(local, data);
    centrals.push(central);
    offset += local.length + data.length;
  }
  const directory = concat(centrals);
  const end = new Uint8Array(22);
  const e = new DataView(end.buffer);
  e.setUint32(0, 0x06054b50, true);
  e.setUint16(8, parts.length, true);
  e.setUint16(10, parts.length, true);
  e.setUint32(12, directory.length, true);
  e.setUint32(16, offset, true);
  return concat([...locals, directory, end]);
}

const out = join(import.meta.dir, '../apps/demo/public/sample.docx');
const bytes = zip(PARTS);
writeFileSync(out, bytes);
console.log(`wrote ${out} (${bytes.length} bytes)`);
